# Generated by Django 5.2.6 on 2025-09-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='course_image',
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='course_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courses/thumbnails'),
        ),
    ]
